# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.cache/wt [current_project]
set_property parent.project_path /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/mxj/workspace/tk2_zynq_hardware/ip_repo [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/new/tk3_top.v
}
add_files /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_1_0/design_1_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_1_0/design_1_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_1_0/design_1_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_2_0/design_1_axi_uartlite_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_2_0/design_1_axi_uartlite_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_2_0/design_1_axi_uartlite_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/constrs_1/system.xdc
set_property used_in_implementation false [get_files /home/mxj/workspace/tk2_zynq_hardware/tk2_linux.srcs/constrs_1/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top tk3_top -part xc7z020clg400-1


write_checkpoint -force -noxdef tk3_top.dcp

catch { report_utilization -file tk3_top_utilization_synth.rpt -pb tk3_top_utilization_synth.pb }
